# Generated by Django 4.2.1 on 2023-05-28 07:55

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, validators=[users.validators.check_age]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Нельзя с такого домена",
                        regex="rambler.ru",
                    )
                ],
            ),
        ),
    ]
